### ISSUE TITLE
idk new crash

### ISSUE THREAD

**Issue by JacketSnS** [rockymoto517/BerserkerBlocker#2]
Application has crashed: C++ exception
mods/BerserkerQOL/lua/berserkerQOL.lua:13: attempt to index field 'multi_profile' (a nil value)

SCRIPT STACK

health_skill_addend() @mods/BerserkerQOL/lua/berserkerQOL.lua:242
fs_reset_max_health() @mods/Full Speed Swarm/lua/playermanager.lua:41
original() @mods/Full Speed Swarm/lua/playermanager.lua:37
init() @mods/base/req/core/Hooks.lua:288
new() core/lib/utils/coreclass.lua:35
original() lib/setups/setup.lua:399
init_managers() @mods/base/req/core/Hooks.lua:288
init_managers() lib/setups/menusetup.lua:291
core/lib/setups/coresetup.lua:399

-------------------------------

Callstack:

         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
         payday2_win32_release  (???)     ???                                                 
                      KERNEL32  (???)     BaseThreadInitThunk                                 
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
                         ntdll  (???)     RtlGetAppContainerNamedObjectPath                   
         payday2_win32_release  (???)     zip_get_name                                        

-------------------------------

Current thread: Main
Script stack:
         health_skill_addend()  @mods/BerserkerQOL/lua/berserkerQOL.lua:242         
         fs_reset_max_health()  @mods/Full                                          
                                Speed                                               
Swarm/lua/playermanager.lua:41  original()                                          
                    @mods/Full                                                      
                         Speed  Swarm/lua/playermanager.lua:37                      
                        init()  @mods/base/req/core/Hooks.lua:288                   
                         new()  core/lib/utils/coreclass.lua:35                     
                    original()  lib/setups/setup.lua:399                            
               init_managers()  @mods/base/req/core/Hooks.lua:288                   
               init_managers()  lib/setups/menusetup.lua:291                        
                                core/lib/setups/coresetup.lua:399                   

-------------------------------

System information:
	Application version : 1.127.120
	CPU : Intel(R) Core(TM) i5-8400 CPU @ 2.80GHz (3 cores); SSE; SSE2; SSE3; SSSE3; SSE4.1; SSE4.2
	DirectX : 12.0 
	GPU : NVIDIA GeForce RTX 2060 / nvldumd.dll[31.0.15.1659]
	Language : english
	Memory :     16303MB 284KB
	OS : 6.2.9200 () 0x100-0x1 (64 bits)
	Physics : threaded
	Renderer : DX9 threaded
	Sound : Realtek Semiconductor Corp. (Speakers (Realtek(R) Audio))

**Comment by rockymoto517** [comment]
Fix https://github.com/rockymoto517/BerserkerBlocker/commit/9857555ba137490fd7449bfe89864d5778a2102c
